export const FETCHING_CATEGORIES = 'FETCH_CATEGORIES';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const FETCHING_FACTS = 'FETCHING_FACTS';
export const FACTS_FETCHED = 'FACTS_FETCHED';
export const MOVE_TO_CUSTOM_LIST = 'MOVE_TO_CUSTOM_LIST';
export const REMOVE_FROM_CUSTOM_LIST = 'REMOVE_FROM_CUSTOM_LIST';
